# fly.toml app configuration file generated for course-service-baydyq on 2025-09-02T22:02:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'course-service-baydyq'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
