POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNjdmYWNjMS1kYjhiLTQwZWYtYWIxZC04YmNkZGFmM2ExZjgiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1Njc2MDY5OX0.FxW59P0rxq5QlsjraXJlBsSuFYzs3WNPX4WGqMXnPds

{
  "title": "Course Developer Backend C#"
}

###

GET http://localhost:3333/sessions

###
GET http://localhost:3333/courses?orderBy=title
###

GET http://localhost:3333/courses/c73228a7-b598-4bc2-8eed-7fc92865031f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjhhYjRkZC0yZmM1LTQzMTMtYjY0OS04YjU3ZTNhM2FlMTciLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjQxMTA4Nn0.Md2B_aDYyvDUtTjEqmJviEHzECT86KXpZsN3Zj5YRfE

###

GET http://localhost:3333/courses?orderBy=title&page=1&pageSize=5

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
"email":"JoaoPedro_Melo5@gmail.com",
"password": "123456"
}
